In [2]:
import sys
print(sys.executable)

/opt/anaconda3/envs/mlflow/bin/python


In [3]:
!python --version

Python 3.9.19


In [3]:
import torch
import numpy

In [6]:
data = [[1, 2],[3, 4]]
a_data = torch.tensor(data)
print(a_data)

tensor([[1, 1],
        [1, 1]])


In [8]:
b_data = torch.rand(2,3)
print(b_data)

tensor([[0.4735, 0.4895, 0.2033],
        [0.1878, 0.4760, 0.1764]])


In [14]:
c_data = torch.ones(2,3)
print(c_data)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
c_data = torch.zeros(2,3)
print(c_data)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
